### ISSUE TITLE
Suggestion: Wings Mod Compat

### ISSUE THREAD

**Issue by SirAron111** [quat1024/BrokenWings#2]
You should add compat for this mod https://www.curseforge.com/minecraft/mc-mods/wings cant seem to get these neat wings to not stop workign in the twilight and other dimensions

**Comment by katubug** [comment]
I second this. I thought it might be considered "elytra-type" flight so I banned that via the config, but it doesn't seem to have worked.

**Comment by quat1024** [comment]
note to self: the magic class is, I think, https://github.com/pau101/Wings/blob/master/src/main/java/me/paulf/wings/server/flight/Flights.java (also useful for autothirdperson)

Been meaning to add more mod compats anyways, never got around to it. Yeah, Wings does its own thing, it's not like elytra.

**Comment by quat1024** [comment]
Done in d0e08ad26b9006c4d51d290ac4e7adc7a6995547

There are a few shortcomings: you still don't take fall damage, and only actually flying with the wings is blocked (you can still float gently down to the ground, etc). I didn't want to get too invasive.

**Comment by quat1024** [comment]
published as 2.1.0 on curse (beta file)

**Comment by katubug** [comment]
Excellent, I think that's a fine compromise. I like the idea of the item still providing some benefit. I'll try it out as soon as I can!
