### ISSUE TITLE
Whitelist item cannot use metadata

### ISSUE THREAD

**Issue by katubug** [quat1024/BrokenWings#4]
Hey, so I wanted to set a particular item to whitelist flight in banned dimensions. However, the item I wanted to use (the "Precious Emerald" from RandomThings), has a metadata/nbt value. The mod seems to be unable to recognize this, but perhaps I'm entering it incorrectly?

I also tested it with a vanilla item with metadata, and neither worked.

I've tried entering it this way: `minecraft:log:3`

And also this way: `randomthings:ingredient@9`

Neither functions as I'd expect. 

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.3](http://enthusiasticraft.cf/modpack-update-1-7-3/#modlist)
* **Mod versions:** brokenwings-2.0.0

Thanks for your time!

**Comment by quat1024** [comment]
Oh, yeah, currently theres no support for metadata values (it's always kind of a pain to add). I'll take a look.

**Comment by katubug** [comment]
That's understandable. Thanks for taking a look! :)

**Comment by quat1024** [comment]
Going to add this in the next version (check the readme for the details on how to use it)

**Comment by quat1024** [comment]
published as 2.1.0 on curse (beta file)
